plutov/practice-go

- chess/chess.go
My solution to the chess problem. :)
> chess solution

- anagram/anagram.go
Hi @plutov, I see your comment in Golang Vietnam's Slack. I don't have much experience in performance optimization. But let try.
> Implement the anagram

- mergesort/mergesort.go
Hi
I implemented merge sort in go.
Please take a look.
Thank you!
> Implemented merge sort

- buildword/buildword.go
Hello. I think this PR satisfies your buildword challenge.
I think that your first test is incorrect: 
{"buildword", []string{"buil", "dwor", "bu", "uild", "wo", "rd"}, 4},
I believe there's no combination of those 6 fragments that will get you to "buildword" - either "bu" should be "be", or "uild" should be "ild"
> Candidate for buildword solution

- sumdecimal/sumdecimal.go
Compute each digit of the square root in a sequence with math package. 
Ref: https://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Decimal_.28base_10.29
> Implemented sumdecimal

- .travis.yml
- README.md
What do you think about having all the submitted solutions automatically tested?
> Added travis-ci.org support

- .travis.yml
... but does not add any real value
> Removed `tip` version of `go` since it takes to long

- lastlettergame/lastlettergame.go
The provided implementation runs in `0.06s` on http://ideone.com/GNAn9S
The path finding algorithm itself is 0 allocations (and presumably index building allocates).
> Implemented lastlettergame

- reverseparentheses/reverseparentheses.go
This solution does not handle multibyte characters, but works fine on the test cases.
> Solution to reverse parentheses

- functionfrequency/functionfrequency.go
This should work for other go files too as it uses the go ast. 
PS http://pliutau.com seems to be down at the moment
> Added solution for function frequency

- functionfrequency/functionfrequency_test.go
Implemented multi-answer unit tests: most files assume different correct answers
> Implemented multiple cases check for unit test

- missingnumbers/missingnumbers.go
Finds missing numbers by solving a quadratic equation. Doesn't use if-statements.
BenchmarkMissing-8               2000000               736 ns/op              48 B/op          3 allocs/op
BenchmarkMissingFuzzy_1e2-8      3000000               537 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e3-8      1000000              1185 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e4-8       200000              9738 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e5-8        20000             78022 ns/op              16 B/op          1 allocs/op
BenchmarkMissingFuzzy_1e6-8         2000            659775 ns/op              16 B/op          1 allocs/op
> mathematical solution

- spiral/spiral.go
> Solution added to the skeleton

- warriors/warriors.go
Using (sort of) an image filter technique to walk the image, marking and counting warriors.
> Warriors solution

- snowflakes/snowflakes.go
- snowflakes/snowflakes_test.go
probably not
brute force
- there is a cyclic triangle generation pattern
- in each iteration sum up generated triangle at their color index
- red and green are also triangles that generate other triangles
- don't show them in the results
time: O(n^2)
space: O(n) - two slices of size n
--------------------------------------------------
BenchmarkOverlaidTriangles-8     3000000               555 ns/op             192 B/op          2 allocs/op
PASS
ok      github.com/shogg/practice-go/snowflakes 2.271s
> red, green - the hidden triangles

- brokennode/brokennode.go
- brokennode/brokennode_test.go
no
no
* space: **O( n )**
* time: **O( n! / ((n/2)!)^2 )**
< **O( 2^n )**
**n! / ((n/2)!)^2** is the worst case number of configurations for n nodes with a fixed number broken
* 26 nodes: 2^26 configurations
* 26 nodes, 13 broken: ~2^23 configurations
* 26 nodes, 3 broken: 2600 configurations (~2^11)
> broken nodes

- lastlettergame/lastlettergame_test.go
- Added checker functions
- Checks multiple solutions
> lastlettergame tester checks multiple solutions resolves issue (#65)

- romannumerals/romannumerals.go
By use of `strings.Builder`, achieved ~2.6x speed increase on `Encode` function. Repeated string concatenations cause multiple memory re-allocations slowing things down
No
Same
> Speed up encode function

- wordladder/wordladder.go
As in anagram we need to use BFS not Dijkstra.
> wordladder

- anagram/anagram.go
Yes. Not changed the algorithm, just simplified the code
No.
The Normalize time complexity is still O(nlogn) where n is the length of the input string, and space complexity is still O(n).
> simplify the code of anagram

- chess/chess.go
- It's twice as fast as current solution
- No, it uses math.Abs instead of hand written abs function.
- I think using 'switch' for co-ord check is a little more readable than the 'if' check
- I use co-ords based on 1 instead of 0 for readability.
- time is a half of current solution (120 ns/op vs 240 ns/op) on my machine
- I don't think there are any space issues, 58 lines of code vs 38.
> Faster implementation using math.Abs and switch
